name: Taski
on:
  push:
    branches:
      - main

jobs:
  check_and_print_tree:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: print tree
        run: tree .
